name: Build and Push Docker Image

on:
  push:
    branches: [ main ]     # Trigger on push to main branch
  workflow_dispatch:       # Allow manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: srujanchinta/ml_project_data_science:latest
